language: node_js
node_js:
- node
- '6'
- '5'
addons:
  ssh_known_hosts: robotscostrent.com
sudo: false
cache:
  directories:
  - node_modules
before_install:
  - mkdir -p ~/.ssh
  - openssl aes-256-cbc -K $encrypted_f99822d1fb4e_key -iv $encrypted_f99822d1fb4e_iv -in deploy-key.enc -out ~/.ssh/deploy-key -d
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - phantomjs --version
install:
  - npm install
  - bower install
script:
  - npm test
after_success:
  - bash .travis/deploy.sh
